### ISSUE TITLE
chapter 11. TypeError: Cannot join tz-naive with tz-aware DatetimeIndex

### ISSUE THREAD

**Issue by JMA6971** [PacktPublishing/Mastering-Python-for-Finance-Second-Edition#1]
df_close "date" is not the same as all the other "technicals" df and trying to join them results in the error:
`TypeError:` Cannot join tz-naive with tz-aware DatetimeIndex` 

I'm sure it's an easy fix for experienced pandas user.  If I figure it out I'll post fix.
edit - try inserting 2nd line here:
`df['date_time'] = pd.to_datetime(df['date_time'])`
`df['date_time'] = df['date_time'].dt.date`
`df = df.set_index('date_time')`

**Comment by sabirjana** [comment]
Please convert df_target.index usinig tz_localize('Etc/UCT') beforing joining all dataframes

df_target.index = pd.to_datetime(df_target.index).tz_localize('Etc/UCT')

**Comment by ManikandanKurup-Packt** [comment]
hi @JMA6971 
can we close the issue if it has been resolved?

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue still persists

**Comment by rnjv** [comment]
I arrived here when I wanted to pd.concat via ignore_index=True with a series with no datetime index
