### ISSUE TITLE
regression model in ch10 not working

### ISSUE THREAD

**Issue by luisvelo** [PacktPublishing/Mastering-Python-for-Finance-Second-Edition#3]
tried to run the code, but linear_reg_model.df_result comes empty.

tried to change date parameters to NA (specific dates instead of 2018-2019), seems to be something different.

**Comment by jamesmawm** [comment]
Hi luisvelo,
It's been noted that Alpha Vantage library is getting unstable.
I've created a temporary fix for this: https://github.com/jamesmawm/mastering-python-for-finance-second-edition/pull/2/files
The updated version of Chapter 10 can be found here: https://github.com/jamesmawm/mastering-python-for-finance-second-edition/blob/master/Chapter%2010%20-%20Machine%20Learning%20for%20Finance.ipynb

The idea is to use a different equity symbol for the time being, until Alpha Vantage resume its service.
