### ISSUE TITLE
no numeric data to plot 

### ISSUE THREAD

**Issue by elvinwangyh** [PacktPublishing/Mastering-Python-for-Finance-Second-Edition#4]
issue with plotting, df_result

TypeError                                 Traceback (most recent call last)
<ipython-input-7-d782f984f974> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 
----> 3 linear_reg_model.df_result.plot(
      4     title='JPM prediction by OLS',
      5     style=['-', '--'], figsize=(12,8));

/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_core.py in __call__(self, *args, **kwargs)
    947                     data.columns = label_name
    948 
--> 949         return plot_backend.plot(data, kind=kind, **kwargs)
    950 
    951     __call__.__doc__ = __doc__

/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/__init__.py in plot(data, kind, **kwargs)
     59             kwargs["ax"] = getattr(ax, "left_ax", ax)
     60     plot_obj = PLOT_CLASSES[kind](data, **kwargs)
---> 61     plot_obj.generate()
     62     plot_obj.draw()
     63     return plot_obj.result

/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py in generate(self)
    267     def generate(self):
    268         self._args_adjust()
--> 269         self._compute_plot_data()
    270         self._setup_subplots()
    271         self._make_plot()

/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py in _compute_plot_data(self)
    416         # no non-numeric frames or series allowed
    417         if is_empty:
--> 418             raise TypeError("no numeric data to plot")
    419 
    420         # GH25587: cast ExtensionArray of pandas (IntegerArray, etc.) to

TypeError: no numeric data to plot

**Comment by jamesmawm** [comment]
Thanks for bringing this up.
A patch has been issued in https://github.com/PacktPublishing/Mastering-Python-for-Finance-Second-Edition/pull/5/files.
You can manually make the change in the meantime.
