### ISSUE TITLE
Chap 7 alpha_vantage SPX & VIX data no longer available

### ISSUE THREAD

**Issue by walksonair** [PacktPublishing/Mastering-Python-for-Finance-Second-Edition#9]
Could I get some help finding substitute data source as I think alpha_vantage no longer provides data for the subject tickers. 

```
symbol='^GSPC'
symbol='^VIX'
```

Strangely `symbol='NDAQ'` still works.

**Update**
I incorrectly assumed NDAQ was Nasdaq index. See comment below and Alpha Vantage website stating indexes no longer supported.

**Comment by walksonair** [comment]
Just found this link but can't verify authenticity: [https://github.com/prediqtiv/alpha-vantage-cookbook/issues/1#issue-654363245](https://github.com/prediqtiv/alpha-vantage-cookbook/issues/1#issue-654363245)

 Could book author provide alternate source?

**Comment by jamesmawm** [comment]
Hi walksonair, you may consider switching to paid sources such as https://intrinio.com/, which is also covered in the book.

Other data sources:
https://firstratedata.com/
https://www.refinitiv.com/en/financial-data/pricing-and-market-data

**Comment by walksonair** [comment]
Thanks @jamesmawm , I was hoping to follow the examples in the book w/o additional cost. I'll check out the links you provided. 

Slightly off topic but is there a database setup in the book I could possibly use to store this data so that I don't have to re-download them every time I run/tweak an example?

**Comment by jamesmawm** [comment]
Sorry for the trouble, but unfortunately Packt and myself were unable to obtain the copyrights to redistribute dataset examples.

As we're working with Pandas `Dataframe` objects mostly, the `to_csv` and `from_csv` methods helps to save and load these data to disk.
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv

**Comment by walksonair** [comment]
Thank you. I'm looking into getting out of CSV and maybe into postgreSQL. Any tips much appreciated! Thanks again!
